#!/usr/bin/python2

import config
import header
import cgi,commands,os

header.header_content()

print ('<div class="main-holder">')
print ('<div class="form-container">')
print ('<form method="get" style="width:373px;" action="docker.py">')
print ('<h2 class="text-center">LAUNCH A CONTAINER</h2>')
print ('<select class="form-control" name="image">')
print ('<optgroup label="This is a group">')
print ('<option value="centos" selected="">CentOS 7</option>')
print ('<option value="ubuntu14.04">Ubuntu 14.04</option>')
print ('<option value="sshimg:v1">CentOS SSH</option>')
print ('</optgroup>')
print ('</select>')
print ('<div class="form-group"></div>')
print ('<div class="form-group">')
print ('<input class="form-control" type="text" name="cname" placeholder="Name">')
print ('</div>')
print ('<div class="table-responsive">')
print ('<table class="table">')
print ('<thead>')
print ('<tr>')
print ('<th colspan="3">Install essentials on container launch:</th>')
print ('</tr>')
print ('</thead>')
print ('<tbody>')
print ('<tr>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="checkbox" name="cbg" value="ssh">SSH</label>')
print ('</div>')
print ('</td>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="checkbox" name="cbg" value="apache">Apache httpd</label>')
print ('</div>')
print ('</td>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="checkbox" value="ngnix" name="cbg">Nginx</label>')
print ('</div>')
print ('</td>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="checkbox" value="htop" name="cbg">htop</label>')
print ('</div>')
print ('</td>')
print ('</tr>')
print ('<tr>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="checkbox" value="">Docker-CE</label>')
print ('</div>')
print ('</td>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="checkbox">Shell-in-the-Box</label>')
print ('</div>')
print ('</td>')
print ('<td style="width:25%;">')
print ('<div class="checkbox">')
print ('<label>')
print ('<input type="text" value="" placeholder="manually add packages name" style="width:100%;"></label>')
print ('</div>')
print ('</td>')
print ('</tr>')
print ('</tbody>')
print ('</table>')
print ('</div>')
print ('<div class="form-group has-success"></div>')
print ('<div class="form-group">')
print ('<button class="btn btn-primary btn-block" style="background-color:#055ada !important;"" type="submit">SUBMIT </button>')
print ('</div>')
print ('</form>')
print ('</div>')
print ('</div>')
print ('<script src="/js/jquery.min.js"></script>')
print ('<script src="/bootstrap/js/bootstrap.min.js"></script>')
print ('</body>')
print ('')
print ('</html>')
