#!/usr/bin/python2

import config
import header
import cgi,commands,os,MySQLdb
import Cookie
import cgitb
cgitb.enable()

header.header_content()

print (' <div class="main-holder"> ')
print (' <div class="form-container" style="width:1000px"> ')
print ('<div class="image-holder" style="background-image:url(&quot;/img/iaas_form.jpg&quot;);margin:10px;padding:20px;"></div>')

print ('<form method="post" action="iaas-launch.py" style="width:350px;margin-right:none;">')
print ('<h2 class="text-center">IAAS </h2>')
print ('<select class="form-control" name="OSName">')
print ('<option value="1" >RHEL7</option>')
print ('<option value="2" >Ubuntu 16.04</option>')
print ('<option value="3" >Fedora Workstation</option>')
print ('<option value="4" >Arch Linux</option>')
print ('</select>')
print ('<div class="form-group"></div>')
print ('<input class="form-control" type="text" name="hypervIP" placeholder="Remote Hypervisor IP">')
print ('<div class="form-group"></div>')
print ('<input class="form-control" type="text" name="OSLabel" placeholder="OS Name/Alias">')
print ('<div class="form-group"></div>')
print ('<input class="form-control" type="number" name="CPUCores" placeholder="CPU Cores" min="1" max="16" step="1">')
print ('<div class="form-group"></div>')
print ('<div class="row">')
print ('<div class="clearfix"></div>')
print ('</div>')
print ('<div class="form-group"></div>')
print ('<div class="table-responsive">')
print ('<table class="table">')
print ('<thead>')
print ('<tr></tr>')
print ('</thead>')
print ('<tbody>')
print ('<tr>')
print ('<td>')
print ('<input type="range" style="height:40px;width:130px" min="512" step="512" max="16384" for="osRAMsize" name="osRAM" oninput="osRAMsize.value=osRAM.value" />')
print ('</td>')
print ('<td>')
print ('<input style="width:110px" type="number" placeholder="RAM Size" class="form-control" min="512" step="512" max="16384" for="osRAM" name="osRAMsize" oninput="osRAM.value=osRAMsize.val" />')
print ('</td>')
print ('<td>')
print ('<span class="input-group-addon"style="height:40px">MB</span>')
print ('</td>')
print ('</tr>')
print ('<tr>')
print ('<td>')
print ('<input type="range" style="height:40px;width:130px" min="8" step="1" max="70" for="osDRIVEsize" name="osDRIVE" oninput="osDRIVEsize.value=osDRIVE.value" />')
print ('</td>')
print ('<td>')
print ('<input style="width:110px" type="number" placeholder="Drive Size" class="form-control" min="8" step="1" max="70" for="osDRIVE" name="osDRIVEsize" oninput="osDRIVE.value=osDRIVEsize.val" />')
print ('</td>')
print ('<td>')
print ('<span class="input-group-addon" style="height:40px">GB</span>')
print ('</td>')
print ('</tr>')
print ('</tbody>')
print ('</table>')
print ('</div>')
print ('<div class="form-group">')
print ('<button class="btn btn-primary btn-block" type="submit">SUBMIT</button>')
print ('</div>')
print ('</form>')
print (' </div> ')
print (' </div> ')
print (' <script src="/js/jquery.min.js"></script> ')
print (' <script src="/bootstrap/js/bootstrap.min.js"></script> ')
print (' <script src="/js/script.min.js"></script> ')
print (' </body> ')
print ('  ')
print (' </html> ')
